//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EMPSYSEntities : DbContext
    {
        public EMPSYSEntities()
            : base("name=EMPSYSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblDept1> tblDept1 { get; set; }
        public DbSet<tblEmp1> tblEmp1 { get; set; }
        public DbSet<tblUser1> tblUser1 { get; set; }
    }
}
