//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class tblEmp1
    {
        public int EmpID { get; set; }
        public string EmpName { get; set; }
        public Nullable<System.DateTime> EmpDOB { get; set; }
        public string EmpGender { get; set; }
        public string EmpEmail { get; set; }
        public string EmpContactNo { get; set; }
        public string EmpDeptName { get; set; }
        public string EmpSalary { get; set; }
        public string EmpPhoto { get; set; }
    }
}
